<?php
/*
/ Template uses data generated by the rea_post_list function() in /library/functions/frontend.php
/
/ Available variables
/ ---------------------
/
*/
//The included variables
	$title;
	$list;

?>
<?php echo '<h4 class="rui-brand-heading">'.$title.'</h4>';  ?>
<ul class="post-list">

    <?php
    foreach($list as $index=>$tag){

        if( $index == 10 ){

             echo '<div class="more hide"><li><a href="'.get_term_link($tag).'">'.$tag->name.'<span>'.$tag->count.'</span></a></li>';

        }else if( count($list) > 10 && $index == count($tag)/2 ){

             echo '<li style="display:none;"><a href="'.get_term_link($tag).'">'.$tag->name.'<span>'.$tag->count.'</span></a></li>';

        }else{

            echo '<li><a href="'.get_term_link($tag).'">'.$tag->name.'<span>'.$tag->count.'</span></a></li>';

        }

    };

    if( count($list) > 10 ){

        echo '</div><a class="show-more-list" href="#"><i>+</i>Show more '.$title.'</a>';

    }

    ?>
</ul>