<?php
/*
/ Template uses data generated by the rea_posts function() in /library/functions/frontend.php
/
/ Available variables
/ ---------------------
/
*/
//The included variables
    $post_id = get_the_id();
    $postUrl = get_permalink();
    $postThumb = NULL;
    $postThumbImg = get_field('post_thumb', $post_id);
    if (!empty($postThumbImg)) {
        $postThumb = wp_get_attachment_image_src($postThumbImg, 'rea-post-thumbnail');
    }
    $author_id = get_the_author_meta('ID');
    $post_date = get_the_time('d M Y', $post_id);
?>

<div class="article-wrapper">
  <h2 class="rui-brand-heading"><a href="<?php echo $postUrl; ?>"><?php the_title(); ?></a></h2>
  <section class="post-meta rui-clearfix">
    <div class="author"><?php echo rea_author_snippet_by_id($author_id); ?>
        <div class="post-date"><?php echo $post_date; ?></div>
    </div>
    <?php get_template_part('partials/topic-list'); ?>
  </section>
</div>
<div class="post-overview">
    <?php if(isset($postThumb)) { ?>
     	<div class="post-thumb">
        <img src="<?php echo $postThumb[0]; ?>" width="<?php echo $postThumb[1]; ?>" height="<?php echo $postThumb[2]; ?>"
         alt="<?php the_title(); ?>"/>

		<?php

        $connected_brand = get_connected_brands($post_id);

		if($connected_brand) {

	    style_frontpage_branded($post_id, $connected_brand, 'category');

	    }
	 	echo '</div>';
     } ?>

    <div class="article-wrapper">
      <div class="excerpt"><?php read_more_excerpt();?></div>
    </div>
</div>


